trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: GOBIN
    value: '$(GOPATH)/bin'
  - name: GOROOT
    value: '/usr/local/go1.16.5'
  - name: GOPATH
    value: '$(system.defaultWorkingDirectory)/gopath'
  - name: modulePath
    value: '$(GOPATH)src/dev.azure.com/coopnorge/Scan-and-pay/_git/db-facade'
  - name: BINARY_NAME
    value: 'db-facade'
  - name: GOFLAGS
    value: -mod=vendor

resources:
  repositories:
    - repository: template
      type: git
      name: Engineering/Engineering

steps:
  - template: pipeline-templates/go-library.yml@template
    parameters:
      goVersion: '1.16.5'
      GOBIN: $(GOBIN)
      GOPATH: $(GOPATH)
      GOROOT: $(GOROOT)
      modulePath: $(modulePath)
      BINARY_NAME: $(BINARY_NAME)
