name: CI/CD
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  mage:
    uses: coopnorge/mage/.github/workflows/mage.yaml@main
    permissions:
      contents: read
      id-token: write
      packages: read
    secrets: inherit

  build:
    needs:
      - mage
    if: always()
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: exit 1
        name: "Catch errors"
        if: |
          needs.mage.result == 'failure'
