---
name: Lint Code Base
on:
  push:
    branches-ignore: [ main ]
jobs:
  # Lint project
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21' ]
    name: Lint Code Base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          # Lint only changed files
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (test.go|generated|vendor)
