---
on: [ pull_request ]
name: validate
jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21' ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v -race -p=1 ./...
  build:
    needs:
      - validate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
